### PR TITLE
change enums with types for better typechecking in rollup config

### PR DESCRIPTION
**Pull request by MrFoxPro**

### CODE REVIEW

**Comment by mentaljam** [comment]
Hi,

Thank you for your contribution! Can you please explain why your approach is better for type checking? As I can see it doesn't fundamentally change checks but breaks partly type documentation.

**Comment by MrFoxPro** [comment]
When I first time installed plugin, I was trying to set `inject `field, and I had no ability to get it works without vscode intellisense errors. Most developers uses rollup config js file and in js file enums does not exist. And string-like type works well.

**Comment by mentaljam** [comment]
Ok, I see. Can you please then make all the type declarations look like

```typescript
export type Inject =
  /** Inject to the `<head>` tag. */
  | 'head'
  /** Inject to the `<body>` tag. */
  | 'body'
}
```

I mean, move the `|` operator to the start of every option.

**Comment by mentaljam** [comment]
Merged

**Pull request closed without merging**
